### ISSUE TITLE
Installation fails if a user does not have a steam folder in their home directory,

### ISSUE THREAD

**Issue by jcstryker** [Infernio/sssm#2]
The script still tries to install a skin for a user on a system with steam installed, but has not been run by a user yet, so no .steam folder exists yet in their home directory. The script should detect this and skip install for this use.

I am installing on arch linux and the .install script in the aur package fails because of other users in my /home directory which have not run steam.

**Comment by Infernio** [comment]
This should be fixed as of v1.2.0. Please reopen if that didn't fix it properly.
